//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Chat
    {
        public int id { get; set; }
        public Nullable<int> itemId { get; set; }
        public int uploadUser { get; set; }
        public int requestUser { get; set; }
        public Nullable<System.DateTime> lastMessageDate { get; set; }
        public string chatStatus { get; set; }
        public Nullable<bool> requestConfirm { get; set; }
        public Nullable<bool> uploadConfirm { get; set; }
        public Nullable<System.DateTime> openChatDate { get; set; }
    
        public virtual S_Item_New S_Item_New { get; set; }
    }
}
