//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_UserFilter
    {
        public int id { get; set; }
        public string email { get; set; }
        public string keyWordType { get; set; }
        public string keyWord { get; set; }
    
        public virtual S_User_New S_User_New { get; set; }
    }
}
