//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_User_Items
    {
        public int id { get; set; }
        public string email { get; set; }
        public Nullable<int> itemId { get; set; }
        public Nullable<System.DateTime> uploadDate { get; set; }
        public string itemStatus { get; set; }
    
        public virtual S_Item_New S_Item_New { get; set; }
        public virtual S_User_New S_User_New { get; set; }
    }
}
