//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_User_New
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public S_User_New()
        {
            this.S_User_Items = new HashSet<S_User_Items>();
            this.S_FavoriteUsers = new HashSet<S_FavoriteUsers>();
            this.S_FavoriteUsers1 = new HashSet<S_FavoriteUsers>();
            this.S_UserFilter = new HashSet<S_UserFilter>();
        }
    
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int phoneNumber { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string profilePicture { get; set; }
        public string residence { get; set; }
        public int radius { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public Nullable<int> avatarlevel { get; set; }
        public Nullable<int> dailySentenceId { get; set; }
        public int numOfPoints { get; set; }
        public string userToken { get; set; }
        public string showItemsFeed { get; set; }
    
        public virtual S_DailySentence S_DailySentence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_User_Items> S_User_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_FavoriteUsers> S_FavoriteUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_FavoriteUsers> S_FavoriteUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_UserFilter> S_UserFilter { get; set; }
    }
}
